name: "Retention Science build play apps for Github Actions"
description: "Builds and pushes a play app"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  service:
    description: "The name of an ECS service. (default: taken from $GITHUB_REPOSITORY)"
    required: false
  ecr_uri:
    description: "ECR, will query for the URI"
    required: false
  env:
    description: "Terraform environment"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
